markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.markdown
  - refresh-post.sh
  - push-site-live.sh
  - make-posh.sh

plugins:
  - jekyll-feed

# rss
title: "Nick Knowlson"
url: "http://nickknowlson.com"
baseurl: ""
description: "Software Developer. Advocate for quality. I enjoy programming, reading, gaming and metal (among many other things)."
author: "Nick Knowlson"

# sitemap plugin
sitemap:
    filename: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/404.xml"
    include_posts:
        - "/index.html"
        - "/blog/index.html"
        - "/blog/archive/index.html"

# portfolio plugin
portfolio_dir: "projects"
skip_related_projects: true
